import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:remember_me_please/core/theme/app_theme.dart';
import 'package:remember_me_please/features/ai_assistant/ai_assistant_state.dart';
import 'package:remember_me_please/features/ai_assistant/views/listening_view.dart';
import 'package:remember_me_please/features/ai_assistant/views/response_view.dart';
import 'package:remember_me_please/features/ai_assistant/views/thinking_view.dart';

/// The root widget for the AI assistant bottom sheet modal.
///
/// Manages the top-level state machine, passing the finalized spoken text and
/// the generated LLM response between the three child views.
///
/// [conversationContext] is an optional raw JSON string of a specific
/// conversation transcript. When provided, the thinking phase uses it instead
/// of the general ObjectBox RAG query so the LLM can answer targeted questions
/// about that conversation.
class AIAssistantModal extends StatefulWidget {
  // Optional transcript JSON injected when opened from ConversationDetailPage
  final String? conversationContext;

  const AIAssistantModal({super.key, this.conversationContext});

  @override
  State<AIAssistantModal> createState() => _AIAssistantModalState();
}

class _AIAssistantModalState extends State<AIAssistantModal> {
  AssistantState _state = AssistantState.listening;

  // The text captured by speech_to_text when the user taps "I am done talking"
  String _spokenText = '';

  // The final response generated by the local LLM, passed to _ResponseView
  String _llmResponse = '';
  String _llmResponseGeneratedAudioPath = '';

  // Transitions the modal to the thinking state with the finalized spoken text
  void _onListeningFinished(String text) {
    setState(() {
      _spokenText = text;
      _state = AssistantState.thinking;
    });
  }

  // Transitions the modal to the response state with the generated LLM output
  void _onThinkingFinished(String response, {String? generatedAudioPath}) {
    setState(() {
      _llmResponse = response;
      if (generatedAudioPath != null) {
        _llmResponseGeneratedAudioPath = generatedAudioPath;
      }
      _state = AssistantState.response;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: AppColors.scaffoldBackground.withValues(alpha: 0.8),
        borderRadius: const BorderRadius.vertical(top: Radius.circular(40)),
      ),
      child: ClipRRect(
        borderRadius: const BorderRadius.vertical(top: Radius.circular(40)),
        child: BackdropFilter(
          filter: ImageFilter.blur(sigmaX: 12, sigmaY: 12),
          child: _buildContent(),
        ),
      ),
    );
  }

  Widget _buildContent() {
    switch (_state) {
      case AssistantState.listening:
        return ListeningView(onFinish: _onListeningFinished);
      case AssistantState.thinking:
        return ThinkingView(
          spokenText: _spokenText,
          // Pass the conversation transcript context through if available
          conversationContext: widget.conversationContext,
          onFinish: _onThinkingFinished,
        );
      case AssistantState.response:
        return ResponseView(
          spokenText: _spokenText,
          llmResponse: _llmResponse,
          llmResponseGeneratedAudioPath: _llmResponseGeneratedAudioPath,

          // Re-entering the listening state for a follow-up question resets
          // spoken text; the previous response is discarded.
          onAskFollowUp: (String query) {
            setState(() {
              _spokenText = query;
              _llmResponse = '';
              _state = AssistantState.thinking;
            });
          },
          onClose: () => Navigator.of(context).pop(),
        );
    }
  }
}
