// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/conversation_model.dart';
import 'data/models/person_model.dart';
import 'data/models/reminder_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4133167228019039184),
    name: 'PersonModel',
    lastPropertyId: const obx_int.IdUid(7, 1350609043957155911),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2379899404649808560),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7089732499169046139),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4577677751589945815),
        name: 'relationship',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6422175461290115376),
        name: 'memoryNote1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3371979461198918683),
        name: 'memoryNote2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1515167593537776430),
        name: 'profilePicturePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1350609043957155911),
        name: 'faceEmbedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(1, 1265011307411470283),
        hnswParams: obx_int.ModelHnswParams(dimensions: 192, distanceType: 1),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 9220936827239966498),
    name: 'ConversationModel',
    lastPropertyId: const obx_int.IdUid(14, 7333083527430620457),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7836984248545509874),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1600122605867605837),
        name: 'personName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7654594625050717614),
        name: 'timeLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1263026101506824461),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5213518469224532524),
        name: 'tagsString',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3047482913095021330),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8195489501468303020),
        name: 'shortTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7155416353154629911),
        name: 'importantDetails',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4517569450265641089),
        name: 'actionsItems',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 842844951519166362),
        name: 'conversationAudioFilePathUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3416009394415691478),
        name: 'transcriptJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7830432068996039742),
        name: 'personImagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7333083527430620457),
        name: 'summaryAudioPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7374516994593523704),
    name: 'ReminderModel',
    lastPropertyId: const obx_int.IdUid(10, 2129682459745530589),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5788253247249445967),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7284991125825728618),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4539243583753912093),
        name: 'time',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8141626704789919372),
        name: 'brandColorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7717677378395741084),
        name: 'containerColorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2201889000744305287),
        name: 'onContainerColorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5800156563968927041),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9080069033753147293),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2129682459745530589),
        name: 'iconIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 7374516994593523704),
    lastIndexId: const obx_int.IdUid(1, 1265011307411470283),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [2811470375273016013],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      7745591463225737960,
      7724536966867340659,
      6406522665543757635,
      5033679203471438001,
      1698322759983632865,
      5872555056867167792,
      9160144774720691495,
      4686682286535609097,
      2757937925693061030,
      8037354277966026354,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    PersonModel: obx_int.EntityDefinition<PersonModel>(
      model: _entities[0],
      toOneRelations: (PersonModel object) => [],
      toManyRelations: (PersonModel object) => {},
      getId: (PersonModel object) => object.id,
      setId: (PersonModel object, int id) {
        object.id = id;
      },
      objectToFB: (PersonModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final relationshipOffset = fbb.writeString(object.relationship);
        final memoryNote1Offset = fbb.writeString(object.memoryNote1);
        final memoryNote2Offset = fbb.writeString(object.memoryNote2);
        final profilePicturePathOffset = fbb.writeString(
          object.profilePicturePath,
        );
        final faceEmbeddingOffset = object.faceEmbedding == null
            ? null
            : fbb.writeListFloat32(object.faceEmbedding!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, relationshipOffset);
        fbb.addOffset(3, memoryNote1Offset);
        fbb.addOffset(4, memoryNote2Offset);
        fbb.addOffset(5, profilePicturePathOffset);
        fbb.addOffset(6, faceEmbeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final relationshipParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final memoryNote1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final memoryNote2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final profilePicturePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final faceEmbeddingParam = const obx_int.Float32ListReader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final object = PersonModel(
          id: idParam,
          name: nameParam,
          relationship: relationshipParam,
          memoryNote1: memoryNote1Param,
          memoryNote2: memoryNote2Param,
          profilePicturePath: profilePicturePathParam,
          faceEmbedding: faceEmbeddingParam,
        );

        return object;
      },
    ),
    ConversationModel: obx_int.EntityDefinition<ConversationModel>(
      model: _entities[1],
      toOneRelations: (ConversationModel object) => [],
      toManyRelations: (ConversationModel object) => {},
      getId: (ConversationModel object) => object.id,
      setId: (ConversationModel object, int id) {
        object.id = id;
      },
      objectToFB: (ConversationModel object, fb.Builder fbb) {
        final personNameOffset = fbb.writeString(object.personName);
        final timeLabelOffset = fbb.writeString(object.timeLabel);
        final summaryOffset = fbb.writeString(object.summary);
        final tagsStringOffset = fbb.writeString(object.tagsString);
        final shortTitleOffset = fbb.writeString(object.shortTitle);
        final importantDetailsOffset = fbb.writeList(
          object.importantDetails.map(fbb.writeString).toList(growable: false),
        );
        final actionsItemsOffset = fbb.writeList(
          object.actionsItems.map(fbb.writeString).toList(growable: false),
        );
        final conversationAudioFilePathUrlOffset = fbb.writeString(
          object.conversationAudioFilePathUrl,
        );
        final transcriptJsonOffset = fbb.writeString(object.transcriptJson);
        final personImagePathOffset = object.personImagePath == null
            ? null
            : fbb.writeString(object.personImagePath!);
        final summaryAudioPathOffset = object.summaryAudioPath == null
            ? null
            : fbb.writeString(object.summaryAudioPath!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, personNameOffset);
        fbb.addOffset(2, timeLabelOffset);
        fbb.addOffset(3, summaryOffset);
        fbb.addOffset(5, tagsStringOffset);
        fbb.addInt64(6, object.createdAt);
        fbb.addOffset(7, shortTitleOffset);
        fbb.addOffset(8, importantDetailsOffset);
        fbb.addOffset(9, actionsItemsOffset);
        fbb.addOffset(10, conversationAudioFilePathUrlOffset);
        fbb.addOffset(11, transcriptJsonOffset);
        fbb.addOffset(12, personImagePathOffset);
        fbb.addOffset(13, summaryAudioPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final shortTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final personNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timeLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final summaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final personImagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final importantDetailsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 20, []);
        final actionsItemsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 22, []);
        final conversationAudioFilePathUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final transcriptJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final summaryAudioPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final tagsStringParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = ConversationModel(
          id: idParam,
          shortTitle: shortTitleParam,
          personName: personNameParam,
          timeLabel: timeLabelParam,
          summary: summaryParam,
          personImagePath: personImagePathParam,
          importantDetails: importantDetailsParam,
          actionsItems: actionsItemsParam,
          conversationAudioFilePathUrl: conversationAudioFilePathUrlParam,
          transcriptJson: transcriptJsonParam,
          summaryAudioPath: summaryAudioPathParam,
          tagsString: tagsStringParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    ReminderModel: obx_int.EntityDefinition<ReminderModel>(
      model: _entities[2],
      toOneRelations: (ReminderModel object) => [],
      toManyRelations: (ReminderModel object) => {},
      getId: (ReminderModel object) => object.id,
      setId: (ReminderModel object, int id) {
        object.id = id;
      },
      objectToFB: (ReminderModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final timeOffset = fbb.writeString(object.time);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, timeOffset);
        fbb.addInt64(4, object.brandColorValue);
        fbb.addInt64(5, object.containerColorValue);
        fbb.addInt64(6, object.onContainerColorValue);
        fbb.addBool(7, object.isCompleted);
        fbb.addInt64(8, object.createdAt);
        fbb.addInt64(9, object.iconIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final iconIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final brandColorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final containerColorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final onContainerColorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object = ReminderModel(
          id: idParam,
          title: titleParam,
          time: timeParam,
          iconIndex: iconIndexParam,
          brandColorValue: brandColorValueParam,
          containerColorValue: containerColorValueParam,
          onContainerColorValue: onContainerColorValueParam,
          isCompleted: isCompletedParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PersonModel] entity fields to define ObjectBox queries.
class PersonModel_ {
  /// See [PersonModel.id].
  static final id = obx.QueryIntegerProperty<PersonModel>(
    _entities[0].properties[0],
  );

  /// See [PersonModel.name].
  static final name = obx.QueryStringProperty<PersonModel>(
    _entities[0].properties[1],
  );

  /// See [PersonModel.relationship].
  static final relationship = obx.QueryStringProperty<PersonModel>(
    _entities[0].properties[2],
  );

  /// See [PersonModel.memoryNote1].
  static final memoryNote1 = obx.QueryStringProperty<PersonModel>(
    _entities[0].properties[3],
  );

  /// See [PersonModel.memoryNote2].
  static final memoryNote2 = obx.QueryStringProperty<PersonModel>(
    _entities[0].properties[4],
  );

  /// See [PersonModel.profilePicturePath].
  static final profilePicturePath = obx.QueryStringProperty<PersonModel>(
    _entities[0].properties[5],
  );

  /// See [PersonModel.faceEmbedding].
  static final faceEmbedding = obx.QueryHnswProperty<PersonModel>(
    _entities[0].properties[6],
  );
}

/// [ConversationModel] entity fields to define ObjectBox queries.
class ConversationModel_ {
  /// See [ConversationModel.id].
  static final id = obx.QueryIntegerProperty<ConversationModel>(
    _entities[1].properties[0],
  );

  /// See [ConversationModel.personName].
  static final personName = obx.QueryStringProperty<ConversationModel>(
    _entities[1].properties[1],
  );

  /// See [ConversationModel.timeLabel].
  static final timeLabel = obx.QueryStringProperty<ConversationModel>(
    _entities[1].properties[2],
  );

  /// See [ConversationModel.summary].
  static final summary = obx.QueryStringProperty<ConversationModel>(
    _entities[1].properties[3],
  );

  /// See [ConversationModel.tagsString].
  static final tagsString = obx.QueryStringProperty<ConversationModel>(
    _entities[1].properties[4],
  );

  /// See [ConversationModel.createdAt].
  static final createdAt = obx.QueryIntegerProperty<ConversationModel>(
    _entities[1].properties[5],
  );

  /// See [ConversationModel.shortTitle].
  static final shortTitle = obx.QueryStringProperty<ConversationModel>(
    _entities[1].properties[6],
  );

  /// See [ConversationModel.importantDetails].
  static final importantDetails =
      obx.QueryStringVectorProperty<ConversationModel>(
        _entities[1].properties[7],
      );

  /// See [ConversationModel.actionsItems].
  static final actionsItems = obx.QueryStringVectorProperty<ConversationModel>(
    _entities[1].properties[8],
  );

  /// See [ConversationModel.conversationAudioFilePathUrl].
  static final conversationAudioFilePathUrl =
      obx.QueryStringProperty<ConversationModel>(_entities[1].properties[9]);

  /// See [ConversationModel.transcriptJson].
  static final transcriptJson = obx.QueryStringProperty<ConversationModel>(
    _entities[1].properties[10],
  );

  /// See [ConversationModel.personImagePath].
  static final personImagePath = obx.QueryStringProperty<ConversationModel>(
    _entities[1].properties[11],
  );

  /// See [ConversationModel.summaryAudioPath].
  static final summaryAudioPath = obx.QueryStringProperty<ConversationModel>(
    _entities[1].properties[12],
  );
}

/// [ReminderModel] entity fields to define ObjectBox queries.
class ReminderModel_ {
  /// See [ReminderModel.id].
  static final id = obx.QueryIntegerProperty<ReminderModel>(
    _entities[2].properties[0],
  );

  /// See [ReminderModel.title].
  static final title = obx.QueryStringProperty<ReminderModel>(
    _entities[2].properties[1],
  );

  /// See [ReminderModel.time].
  static final time = obx.QueryStringProperty<ReminderModel>(
    _entities[2].properties[2],
  );

  /// See [ReminderModel.brandColorValue].
  static final brandColorValue = obx.QueryIntegerProperty<ReminderModel>(
    _entities[2].properties[3],
  );

  /// See [ReminderModel.containerColorValue].
  static final containerColorValue = obx.QueryIntegerProperty<ReminderModel>(
    _entities[2].properties[4],
  );

  /// See [ReminderModel.onContainerColorValue].
  static final onContainerColorValue = obx.QueryIntegerProperty<ReminderModel>(
    _entities[2].properties[5],
  );

  /// See [ReminderModel.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<ReminderModel>(
    _entities[2].properties[6],
  );

  /// See [ReminderModel.createdAt].
  static final createdAt = obx.QueryIntegerProperty<ReminderModel>(
    _entities[2].properties[7],
  );

  /// See [ReminderModel.iconIndex].
  static final iconIndex = obx.QueryIntegerProperty<ReminderModel>(
    _entities[2].properties[8],
  );
}
