import 'dart:async';
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';
import 'package:remember_me_please/core/services/tts_service.dart';
import 'package:remember_me_please/core/theme/app_theme.dart';

/// Displays the LLM-generated response and quick-action suggestion buttons.
///
/// All data is dynamic — there is no static placeholder text. The two quick
/// action buttons each trigger a predefined ObjectBox query and route the
/// result through the LLM by calling [onAskFollowUp].
/// Displays the LLM-generated response and quick-action suggestion buttons.
///
/// All data is dynamic — there is no static placeholder text. The two quick
/// action buttons each trigger a predefined ObjectBox query and route the
/// result through the LLM by calling [onAskFollowUp].
class ResponseView extends StatefulWidget {
  final String spokenText;
  final String llmResponse;
  final String llmResponseGeneratedAudioPath;

  final void Function(String query) onAskFollowUp;
  final VoidCallback onClose;

  const ResponseView({
    required this.spokenText,
    required this.llmResponse,
    required this.llmResponseGeneratedAudioPath,
    required this.onAskFollowUp,
    required this.onClose,
  });

  @override
  State<ResponseView> createState() => _ResponseViewState();
}

class _ResponseViewState extends State<ResponseView> {
  // Flag indicating if the audio is currently playing.
  bool _isPlaying = false;

  // Flag indicating if the audio file is being generated by the TTS service.
  bool _isLoadingAudio = false;

  // Stream subscription for TTS player state
  StreamSubscription<PlayerState>? _ttsSubscription;

  @override
  void initState() {
    super.initState();

    _isPlaying = TtsService().isPlaying;

    // Listen to global TTS player state changes to update the UI.
    _ttsSubscription = TtsService().playerStateStream.listen((
      PlayerState state,
    ) {
      if (mounted) {
        setState(() {
          _isPlaying = state == PlayerState.playing;
        });
      }
    });
  }

  @override
  void dispose() {
    _ttsSubscription?.cancel();
    super.dispose();
  }

  /// Toggles playback of the TTS audio.
  ///
  /// If already playing, stops playback. Otherwise, invokes the
  /// TTS service to generate a new audio file and then plays it.
  Future<void> _togglePlayback() async {
    if (_isLoadingAudio) return;

    if (_isPlaying) {
      await TtsService().stop();
      return;
    }

    setState(() {
      _isLoadingAudio = true;
    });

    try {
      // Use TtsService's speak method which handles caching, generation, and playback
      await TtsService().speak(
        widget.llmResponse,
        audioPath: widget.llmResponseGeneratedAudioPath,
      );
    } catch (e) {
      debugPrint('Error playing TTS in ResponseView: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Failed to generate audio response.')),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoadingAudio = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.fromLTRB(32, 24, 32, 40),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Align(
              alignment: Alignment.topLeft,
              child: IconButton(
                onPressed: widget.onClose,
                icon: const Icon(Icons.close, size: 32),
                color: AppColors.onSurface,
              ),
            ),
            const SizedBox(height: 32),

            // Header row: icon + title
            Row(
              children: [
                Container(
                  width: 64,
                  height: 64,
                  decoration: const BoxDecoration(
                    color: AppColors.primaryContainer,
                    shape: BoxShape.circle,
                  ),
                  child: const Icon(
                    Icons.auto_awesome,
                    color: AppColors.onPrimaryContainer,
                    size: 32,
                  ),
                ),
                const SizedBox(width: 16),
                const Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Your Memory Assistant',
                        style: TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                          color: AppColors.onSurface,
                        ),
                      ),
                      Text(
                        'Here is what I found for you.',
                        style: TextStyle(
                          fontSize: 16,
                          color: AppColors.onSurfaceVariant,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 32),

            // The dynamic LLM response card — no static placeholder text
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: AppColors.surfaceContainerLowest,
                borderRadius: BorderRadius.circular(24),
                boxShadow: [
                  BoxShadow(
                    color: AppColors.onSurface.withValues(alpha: 0.04),
                    blurRadius: 16,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: Text(
                widget.llmResponse,
                style: const TextStyle(
                  fontSize: 20,
                  height: 1.5,
                  color: AppColors.onSurface,
                ),
              ),
            ),
            const SizedBox(height: 16),

            // Read aloud action button wired to Kokoro TTS and audio player
            GestureDetector(
              onTap: _togglePlayback,
              child: Container(
                height: 64,
                decoration: BoxDecoration(
                  color: AppColors.primaryContainer,
                  borderRadius: BorderRadius.circular(32),
                  boxShadow: [
                    BoxShadow(
                      color: AppColors.black.withValues(alpha: 0.06),
                      blurRadius: 16,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Center(
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      if (_isLoadingAudio)
                        const SizedBox(
                          width: 22,
                          height: 22,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: AppColors.onPrimaryContainer,
                          ),
                        )
                      else
                        Icon(
                          _isPlaying ? Icons.stop : Icons.volume_up,
                          color: AppColors.onPrimaryContainer,
                          size: 22,
                        ),
                      const SizedBox(width: 8),
                      Text(
                        _isLoadingAudio
                            ? 'Generating audio...'
                            : (_isPlaying ? 'Stop' : 'Read aloud'),
                        style: const TextStyle(
                          color: AppColors.onPrimaryContainer,
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
            const SizedBox(height: 40),

            const Text(
              'What else would you like to explore?',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: AppColors.onSurface,
              ),
            ),
            const SizedBox(height: 20),

            // Quick action: triggers a predefined reminder-focused query
            _buildSuggestedAction(
              label: 'What should I remember today?',
              icon: Icons.psychology,
              color: AppColors.secondaryContainer,
              onColor: AppColors.onSecondaryContainer,
              onTap: () =>
                  widget.onAskFollowUp('What should I remember today?'),
            ),
            const SizedBox(height: 12),

            // Quick action: triggers a predefined conversation-focused query
            _buildSuggestedAction(
              label: 'Who did I talk to yesterday?',
              icon: Icons.record_voice_over,
              color: AppColors.primaryContainer,
              onColor: AppColors.onPrimaryContainer,
              onTap: () => widget.onAskFollowUp('Who did I talk to yesterday?'),
            ),
            const SizedBox(height: 32),

            ElevatedButton.icon(
              onPressed: widget.onClose,
              icon: const Icon(Icons.expand_more),
              label: const Text(
                'Close Assistant',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.primary,
                foregroundColor: AppColors.onPrimary,
                minimumSize: const Size(double.infinity, 72),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(36),
                ),
                elevation: 0,
              ),
            ),
          ],
        ),
      ),
    );
  }

  /// Builds a tappable suggestion card that fires a predefined query.
  Widget _buildSuggestedAction({
    required String label,
    required IconData icon,
    required Color color,
    required Color onColor,
    required VoidCallback onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(20),
        ),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: onColor.withValues(alpha: 0.1),
                shape: BoxShape.circle,
              ),
              child: Icon(icon, color: onColor, size: 28),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Text(
                label,
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w600,
                  color: onColor,
                ),
              ),
            ),
            Icon(Icons.chevron_right, color: onColor),
          ],
        ),
      ),
    );
  }
}
