import 'dart:async';
import 'dart:ui';
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';
import 'package:speech_to_text/speech_to_text.dart' as stt;
import '../theme/app_theme.dart';
import '../services/llm_service.dart';
import '../services/tts_service.dart';
import '../utils/llm_prompt_builder.dart';
import '../../data/sources/local/objectbox_service.dart';

// Represents the three sequential states of the AI assistant interaction.
enum AssistantState { listening, thinking, response }

/// The root widget for the AI assistant bottom sheet modal.
///
/// Manages the top-level state machine, passing the finalized spoken text and
/// the generated LLM response between the three child views.
///
/// [conversationContext] is an optional raw JSON string of a specific
/// conversation transcript. When provided, the thinking phase uses it instead
/// of the general ObjectBox RAG query so the LLM can answer targeted questions
/// about that conversation.
class AIAssistantModal extends StatefulWidget {
  // Optional transcript JSON injected when opened from ConversationDetailPage
  final String? conversationContext;

  const AIAssistantModal({super.key, this.conversationContext});

  @override
  State<AIAssistantModal> createState() => _AIAssistantModalState();
}

class _AIAssistantModalState extends State<AIAssistantModal> {
  AssistantState _state = AssistantState.listening;

  // The text captured by speech_to_text when the user taps "I am done talking"
  String _spokenText = '';

  // The final response generated by the local LLM, passed to _ResponseView
  String _llmResponse = '';

  // Transitions the modal to the thinking state with the finalized spoken text
  void _onListeningFinished(String text) {
    setState(() {
      _spokenText = text;
      _state = AssistantState.thinking;
    });
  }

  // Transitions the modal to the response state with the generated LLM output
  void _onThinkingFinished(String response) {
    setState(() {
      _llmResponse = response;
      _state = AssistantState.response;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: AppColors.scaffoldBackground.withValues(alpha: 0.8),
        borderRadius: const BorderRadius.vertical(top: Radius.circular(40)),
      ),
      child: ClipRRect(
        borderRadius: const BorderRadius.vertical(top: Radius.circular(40)),
        child: BackdropFilter(
          filter: ImageFilter.blur(sigmaX: 12, sigmaY: 12),
          child: _buildContent(),
        ),
      ),
    );
  }

  Widget _buildContent() {
    switch (_state) {
      case AssistantState.listening:
        return _ListeningView(onFinish: _onListeningFinished);
      case AssistantState.thinking:
        return _ThinkingView(
          spokenText: _spokenText,
          // Pass the conversation transcript context through if available
          conversationContext: widget.conversationContext,
          onFinish: _onThinkingFinished,
        );
      case AssistantState.response:
        return _ResponseView(
          spokenText: _spokenText,
          llmResponse: _llmResponse,
          // Re-entering the listening state for a follow-up question resets
          // spoken text; the previous response is discarded.
          onAskFollowUp: (String query) {
            setState(() {
              _spokenText = query;
              _llmResponse = '';
              _state = AssistantState.thinking;
            });
          },
          onClose: () => Navigator.of(context).pop(),
        );
    }
  }
}

// ---------------------------------------------------------------------------
// Listening View
// ---------------------------------------------------------------------------

/// Displays the mic icon and live speech-to-text transcript.
///
/// Starts listening immediately on mount. When the user taps "I am done
/// talking", it stops the listener and forwards the recognized text upstream.
class _ListeningView extends StatefulWidget {
  final void Function(String text) onFinish;
  const _ListeningView({required this.onFinish});

  @override
  State<_ListeningView> createState() => _ListeningViewState();
}

class _ListeningViewState extends State<_ListeningView> {
  final stt.SpeechToText _speechToText = stt.SpeechToText();
  bool _isListening = false;
  String _text = '';

  @override
  void initState() {
    super.initState();
    _initSpeech();
  }

  void _initSpeech() async {
    final available = await _speechToText.initialize(
      onStatus: (val) => debugPrint('SpeechToText status: $val'),
      onError: (val) => debugPrint('SpeechToText error: $val'),
    );
    if (available) {
      setState(() => _isListening = true);
      _speechToText.listen(
        onResult: (val) => setState(() {
          _text = val.recognizedWords;
        }),
      );
    }
  }

  @override
  void dispose() {
    _speechToText.stop();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 40),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Align(
            alignment: Alignment.topRight,
            child: IconButton(
              icon: const Icon(
                Icons.close,
                color: AppColors.onSurface,
                size: 28,
              ),
              onPressed: () => Navigator.of(context).pop(),
            ),
          ),
          const SizedBox(height: 20),
          Container(
            width: 100,
            height: 100,
            decoration: const BoxDecoration(
              color: AppColors.primary,
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.mic, color: AppColors.onPrimary, size: 48),
          ),
          const SizedBox(height: 40),
          Text(
            _isListening ? 'Listening...' : 'Initializing...',
            style: Theme.of(context).textTheme.displaySmall?.copyWith(
              fontWeight: FontWeight.w300,
              color: AppColors.onSurface,
            ),
          ),
          const SizedBox(height: 16),
          Text(
            _text.isEmpty
                ? "Take your time. I'm right here when you're ready to speak."
                : _text,
            textAlign: TextAlign.center,
            style: Theme.of(
              context,
            ).textTheme.bodyLarge?.copyWith(color: AppColors.onSurfaceVariant),
          ),
          const SizedBox(height: 48),
          SizedBox(
            width: double.infinity,
            height: 64,
            child: FilledButton(
              onPressed: () {
                _speechToText.stop();
                // Pass the captured text up; fall back to a generic query if
                // speech recognition did not return anything.
                final finalText = _text.trim().isNotEmpty
                    ? _text.trim()
                    : 'What should I remember today?';
                widget.onFinish(finalText);
              },
              style: FilledButton.styleFrom(
                backgroundColor: AppColors.primary,
                foregroundColor: AppColors.onPrimary,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(32),
                ),
              ),
              child: const Text(
                'I am done talking',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Thinking View
// ---------------------------------------------------------------------------

/// Runs the RAG pipeline while displaying a loading indicator.
///
/// On mount it retrieves context from ObjectBox, builds the LLM prompt via
/// LlmPromptBuilder, and streams the response from LlmService. Once the
/// stream is complete, it calls [onFinish] with the full response string.
///
/// When [conversationContext] is provided (non-null), the pipeline uses that
/// specific transcript instead of the ObjectBox RAG query.
class _ThinkingView extends StatefulWidget {
  final String spokenText;
  // Optional transcript JSON from a specific conversation (for "Ask about")
  final String? conversationContext;
  final void Function(String response) onFinish;

  const _ThinkingView({
    required this.spokenText,
    this.conversationContext,
    required this.onFinish,
  });

  @override
  State<_ThinkingView> createState() => _ThinkingViewState();
}

class _ThinkingViewState extends State<_ThinkingView> {
  final LlmService _llmService = LlmService();
  final ObjectBoxService _objectBoxService = ObjectBoxService();

  @override
  void initState() {
    super.initState();
    _runRagPipeline();
  }

  void _runRagPipeline() async {
    String prompt;

    if (widget.conversationContext != null &&
        widget.conversationContext!.isNotEmpty) {
      // The user tapped "Ask about" on a specific conversation, so use its
      // transcript JSON as context instead of the general ObjectBox query.
      prompt = LlmPromptBuilder.buildConversationContextPrompt(
        userQuery: widget.spokenText,
        transcriptJson: widget.conversationContext!,
      );
    } else {
      // General assistant flow: retrieve matching context from ObjectBox
      final context = _objectBoxService.retrieveContextForQuery(
        widget.spokenText,
      );
      prompt = LlmPromptBuilder.buildRagPrompt(
        userQuery: widget.spokenText,
        retrievedContext: context,
      );
    }

    // Stream the LLM response, accumulating tokens into a buffer
    final responseBuffer = StringBuffer();

    await _llmService.generateAssistantResponse(
      prompt: prompt,
      onToken: (token) => responseBuffer.write(token),
      onDone: () {
        final result = responseBuffer.toString().trim();
        // Provide a graceful fallback when the model returns nothing
        widget.onFinish(
          result.isNotEmpty
              ? result
              : 'I was unable to find a relevant answer in your memories.',
        );
      },
      onError: (error) {
        debugPrint('RAG pipeline error: $error');
        widget.onFinish(
          'Something went wrong while searching your memories. Please try again.',
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 80),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 120,
            height: 120,
            decoration: BoxDecoration(
              color: AppColors.primaryContainer.withValues(alpha: 0.3),
              shape: BoxShape.circle,
            ),
            child: Center(
              child: Container(
                width: 64,
                height: 64,
                decoration: const BoxDecoration(
                  color: AppColors.primary,
                  shape: BoxShape.circle,
                ),
                child: const Icon(
                  Icons.auto_awesome,
                  color: AppColors.onPrimary,
                  size: 32,
                ),
              ),
            ),
          ),
          const SizedBox(height: 40),
          Text(
            'Thinking...',
            style: Theme.of(context).textTheme.headlineMedium?.copyWith(
              fontWeight: FontWeight.w600,
              color: AppColors.onSurface,
            ),
          ),
          const SizedBox(height: 16),
          Text(
            "I'm looking back through your memories and preparing a thoughtful response.",
            textAlign: TextAlign.center,
            style: Theme.of(
              context,
            ).textTheme.bodyLarge?.copyWith(color: AppColors.onSurfaceVariant),
          ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Response View
// ---------------------------------------------------------------------------

/// Displays the LLM-generated response and quick-action suggestion buttons.
///
/// All data is dynamic — there is no static placeholder text. The two quick
/// action buttons each trigger a predefined ObjectBox query and route the
/// result through the LLM by calling [onAskFollowUp].
/// Displays the LLM-generated response and quick-action suggestion buttons.
///
/// All data is dynamic — there is no static placeholder text. The two quick
/// action buttons each trigger a predefined ObjectBox query and route the
/// result through the LLM by calling [onAskFollowUp].
class _ResponseView extends StatefulWidget {
  final String spokenText;
  final String llmResponse;
  final void Function(String query) onAskFollowUp;
  final VoidCallback onClose;

  const _ResponseView({
    required this.spokenText,
    required this.llmResponse,
    required this.onAskFollowUp,
    required this.onClose,
  });

  @override
  State<_ResponseView> createState() => _ResponseViewState();
}

class _ResponseViewState extends State<_ResponseView> {
  // Flag indicating if the audio is currently playing.
  bool _isPlaying = false;

  // Flag indicating if the audio file is being generated by the TTS service.
  bool _isLoadingAudio = false;

  // Stream subscription for TTS player state
  StreamSubscription<PlayerState>? _ttsSubscription;

  @override
  void initState() {
    super.initState();

    _isPlaying = TtsService().isPlaying;

    // Listen to global TTS player state changes to update the UI.
    _ttsSubscription = TtsService().playerStateStream.listen((PlayerState state) {
      if (mounted) {
        setState(() {
          _isPlaying = state == PlayerState.playing;
        });
      }
    });
  }

  @override
  void dispose() {
    _ttsSubscription?.cancel();
    super.dispose();
  }

  /// Toggles playback of the TTS audio.
  ///
  /// If already playing, stops playback. Otherwise, invokes the
  /// TTS service to generate a new audio file and then plays it.
  Future<void> _togglePlayback() async {
    if (_isLoadingAudio) return;

    if (_isPlaying) {
      await TtsService().stop();
      return;
    }

    setState(() {
      _isLoadingAudio = true;
    });

    try {
      // Use TtsService's speak method which handles caching, generation, and playback
      await TtsService().speak(widget.llmResponse);
    } catch (e) {
      debugPrint('Error playing TTS in ResponseView: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Failed to generate audio response.'),
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoadingAudio = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.fromLTRB(32, 24, 32, 40),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Align(
              alignment: Alignment.topLeft,
              child: IconButton(
                onPressed: widget.onClose,
                icon: const Icon(Icons.close, size: 32),
                color: AppColors.onSurface,
              ),
            ),
            const SizedBox(height: 32),

            // Header row: icon + title
            Row(
              children: [
                Container(
                  width: 64,
                  height: 64,
                  decoration: const BoxDecoration(
                    color: AppColors.primaryContainer,
                    shape: BoxShape.circle,
                  ),
                  child: const Icon(
                    Icons.auto_awesome,
                    color: AppColors.onPrimaryContainer,
                    size: 32,
                  ),
                ),
                const SizedBox(width: 16),
                const Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Your Memory Assistant',
                        style: TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                          color: AppColors.onSurface,
                        ),
                      ),
                      Text(
                        'Here is what I found for you.',
                        style: TextStyle(
                          fontSize: 16,
                          color: AppColors.onSurfaceVariant,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 32),

            // The dynamic LLM response card — no static placeholder text
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: AppColors.surfaceContainerLowest,
                borderRadius: BorderRadius.circular(24),
                boxShadow: [
                  BoxShadow(
                    color: AppColors.onSurface.withValues(alpha: 0.04),
                    blurRadius: 16,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: Text(
                widget.llmResponse,
                style: const TextStyle(
                  fontSize: 20,
                  height: 1.5,
                  color: AppColors.onSurface,
                ),
              ),
            ),
            const SizedBox(height: 16),

            // Read aloud action button wired to Kokoro TTS and audio player
            GestureDetector(
              onTap: _togglePlayback,
              child: Container(
                height: 64,
                decoration: BoxDecoration(
                  color: AppColors.primaryContainer,
                  borderRadius: BorderRadius.circular(32),
                  boxShadow: [
                    BoxShadow(
                      color: AppColors.black.withValues(alpha: 0.06),
                      blurRadius: 16,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Center(
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      if (_isLoadingAudio)
                        const SizedBox(
                          width: 22,
                          height: 22,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: AppColors.onPrimaryContainer,
                          ),
                        )
                      else
                        Icon(
                          _isPlaying ? Icons.stop : Icons.volume_up,
                          color: AppColors.onPrimaryContainer,
                          size: 22,
                        ),
                      const SizedBox(width: 8),
                      Text(
                        _isLoadingAudio
                            ? 'Generating audio...'
                            : (_isPlaying ? 'Stop' : 'Read aloud'),
                        style: const TextStyle(
                          color: AppColors.onPrimaryContainer,
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
            const SizedBox(height: 40),

            const Text(
              'What else would you like to explore?',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: AppColors.onSurface,
              ),
            ),
            const SizedBox(height: 20),

            // Quick action: triggers a predefined reminder-focused query
            _buildSuggestedAction(
              label: 'What should I remember today?',
              icon: Icons.psychology,
              color: AppColors.secondaryContainer,
              onColor: AppColors.onSecondaryContainer,
              onTap: () => widget.onAskFollowUp('What should I remember today?'),
            ),
            const SizedBox(height: 12),

            // Quick action: triggers a predefined conversation-focused query
            _buildSuggestedAction(
              label: 'Who did I talk to yesterday?',
              icon: Icons.record_voice_over,
              color: AppColors.primaryContainer,
              onColor: AppColors.onPrimaryContainer,
              onTap: () => widget.onAskFollowUp('Who did I talk to yesterday?'),
            ),
            const SizedBox(height: 32),

            ElevatedButton.icon(
              onPressed: widget.onClose,
              icon: const Icon(Icons.expand_more),
              label: const Text(
                'Close Assistant',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.primary,
                foregroundColor: AppColors.onPrimary,
                minimumSize: const Size(double.infinity, 72),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(36),
                ),
                elevation: 0,
              ),
            ),
          ],
        ),
      ),
    );
  }

  /// Builds a tappable suggestion card that fires a predefined query.
  Widget _buildSuggestedAction({
    required String label,
    required IconData icon,
    required Color color,
    required Color onColor,
    required VoidCallback onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(20),
        ),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: onColor.withValues(alpha: 0.1),
                shape: BoxShape.circle,
              ),
              child: Icon(icon, color: onColor, size: 28),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Text(
                label,
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w600,
                  color: onColor,
                ),
              ),
            ),
            Icon(Icons.chevron_right, color: onColor),
          ],
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// Opens the AI assistant as a full-height draggable bottom sheet.
///
/// Pass [conversationContext] (a raw JSON string of a conversation transcript)
/// when opening from the ConversationDetailPage "Ask about" button so the LLM
/// answers questions grounded in that specific conversation.
void showAIAssistantModal(BuildContext context, {String? conversationContext}) {
  showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    backgroundColor: AppColors.transparent,
    builder: (context) => AIAssistantModal(
      conversationContext: conversationContext,
    ),
  );
}
